"""
Django settings for sensorcloud project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "sensorcloud.settings")

# settings.py
SNS_TOPIC_ARN = "arn:aws:sns:us-east-1:932875213474:UserRegistrationTopic"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wu2y0vi7#rqf1mr4rk_g_7(t7fbr*$0*j*unt!(#!hjtk358!y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    os.getenv("C9_HOSTNAME"), # Allow Cloud9 hostname
    'b36ebe711382402f91c8f5e12759db30.vfs.cloud9.us-east-1.amazonaws.com',
    "*"
]

CSRF_TRUSTED_ORIGINS = [
    f"https://{os.getenv('C9_HOSTNAME')}"  # Trust Cloud9 URL for CSRF
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django_extensions",
    'rest_framework',
    'corsheaders',
    'users',
    'devices',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:8080",  
]

# Disable CSRF for API calls (Only if needed)
CSRF_TRUSTED_ORIGINS = ["http://127.0.0.1:8080"]
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False    

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}

ROOT_URLCONF = 'sensorcloud.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),  # Project-wide templates
            os.path.join(BASE_DIR, 'users/templates'),  # App-specific templates
            ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sensorcloud.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LOGIN_URL = '/login/' 
LOGIN_REDIRECT_URL = '/dashboard/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


STATIC_URL = "/static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# """
# Django settings for sensorcloud project.
# """

# from pathlib import Path
# import os

# # Build paths
# BASE_DIR = Path(__file__).resolve().parent.parent
# os.environ.setdefault("DJANGO_SETTINGS_MODULE", "sensorcloud.settings")

# # AWS SNS Settings
# SNS_TOPIC_ARN = "arn:aws:sns:us-east-1:932875213474:UserRegistrationTopic"

# # Security Settings
# SECRET_KEY = 'django-insecure-wu2y0vi7#rqf1mr4rk_g_7(t7fbr*$0*j*unt!(#!hjtk358!y'
# DEBUG = True

# ALLOWED_HOSTS = [
#     "localhost",
#     "127.0.0.1",
#     os.getenv("C9_HOSTNAME"),
#     'b36ebe711382402f91c8f5e12759db30.vfs.cloud9.us-east-1.amazonaws.com',
#     "*"
# ]

# # Application definition - Minimal setup
# INSTALLED_APPS = [
#     'django.contrib.contenttypes',  # Required for sessions
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     "django_extensions",
#     'rest_framework',
#     'corsheaders',
#     'users',
#     'devices',
# ]

# MIDDLEWARE = [
#     'corsheaders.middleware.CorsMiddleware',
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'users.middleware.DisableDjangoAuthMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# # Disable Django's auth system completely
# AUTHENTICATION_BACKENDS = []

# # Session Settings
# SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds
# SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
# SESSION_COOKIE_HTTPONLY = True
# SESSION_COOKIE_SAMESITE = 'Lax'

# # REST Framework Settings
# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': [],
#     'DEFAULT_PERMISSION_CLASSES': [
#         'rest_framework.permissions.AllowAny',
#     ],
# }

# ROOT_URLCONF = 'sensorcloud.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [
#             os.path.join(BASE_DIR, 'templates'),
#             os.path.join(BASE_DIR, 'users/templates'),
#         ],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'sensorcloud.wsgi.application'

# # Database Configuration (minimal)
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.dummy',  # Using dummy since we're not using Django's ORM
#     }
# }

# # Internationalization
# LANGUAGE_CODE = 'en-us'
# TIME_ZONE = 'UTC'
# USE_I18N = True
# USE_TZ = True

# # Authentication URLs
# LOGIN_URL = '/login/'
# LOGIN_REDIRECT_URL = '/dashboard/'
# LOGOUT_REDIRECT_URL = '/login/'

# # Static files
# STATIC_URL = "/static/"
# STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

# # Default primary key field type
# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'